"""Generate golden vectors binding the Python feature contract to the C runtime.

Produces two artefacts from the same deterministic inputs:

* ``embedded/tests/golden_vectors.h`` — a C header the host test compiles against,
* ``embedded/tests/golden_vectors.json`` — the same data, for the Python test.

Both are generated from the Python implementation, so the C runtime is checked
against the reference. Tolerances are declared here, not in the test, so a
disagreement is a contract change rather than a test tweak.

Usage::

    python tools/gen_golden_vectors.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import numpy as np

from sofia_ai.features import extract_from_array
from sofia_ai.features.statistical import STATISTICAL_FEATURE_NAMES

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_H = REPO_ROOT / "embedded" / "tests" / "golden_vectors.h"
OUT_JSON = REPO_ROOT / "embedded" / "tests" / "golden_vectors.json"

#: Absolute tolerance for double-precision comparison between Python and C.
#: 1e-9 is loose enough for differing libm implementations and strict enough to
#: catch a real algorithmic divergence.
TOLERANCE = 1e-9

CASES: tuple[dict[str, Any], ...] = (
    {"name": "constant_3", "n": 64, "sample_rate": 1000.0,
     "signal": lambda t: np.full_like(t, 3.0)},
    {"name": "sine_25hz", "n": 256, "sample_rate": 1000.0,
     "signal": lambda t: np.sin(2.0 * np.pi * 25.0 * t)},
    {"name": "sine_50hz_plus_harmonic", "n": 256, "sample_rate": 1000.0,
     "signal": lambda t: np.sin(2.0 * np.pi * 50.0 * t)
     + 0.3 * np.sin(2.0 * np.pi * 100.0 * t)},
    {"name": "dc_offset_ramp", "n": 128, "sample_rate": 1000.0,
     "signal": lambda t: 0.5 * t + 2.0},
    {"name": "impulsive", "n": 256, "sample_rate": 2000.0,
     "signal": lambda t: np.where(
         (np.arange(t.size) % 64) == 0, 5.0, 0.05 * np.sin(2.0 * np.pi * 30.0 * t))},
)


def build_case(spec: dict[str, Any]) -> dict[str, Any]:
    """Compute Python features for one case."""
    n = int(spec["n"])
    sample_rate = float(spec["sample_rate"])
    t = np.arange(n, dtype=np.float64) / sample_rate
    signal = np.asarray(spec["signal"](t), dtype=np.float64)
    vector = extract_from_array(signal, sample_rate)
    table = vector.as_dict()
    return {
        "name": str(spec["name"]),
        "n": n,
        "sample_rate": sample_rate,
        "samples": [float(v) for v in signal],
        "expected": {name: float(table[name]) for name in STATISTICAL_FEATURE_NAMES},
    }


def write_header(cases: list[dict[str, Any]], path: Path) -> None:
    """Emit a C header with static const arrays. Generated file: do not edit."""
    lines = [
        "/* Generated by tools/gen_golden_vectors.py -- DO NOT EDIT */",
        "#ifndef SOFIA_GOLDEN_VECTORS_H",
        "#define SOFIA_GOLDEN_VECTORS_H",
        "",
        "#include <stddef.h>",
        "",
        f"#define SOFIA_GOLDEN_TOLERANCE {TOLERANCE:.1e}",
        f"#define SOFIA_GOLDEN_N_CASES {len(cases)}",
        f"#define SOFIA_GOLDEN_N_FEATURES {len(STATISTICAL_FEATURE_NAMES)}",
        "",
        "typedef struct {",
        "    const char *name;",
        "    size_t n;",
        "    double sample_rate;",
        "    const double *samples;",
        "    const double *expected;",
        "} sofia_golden_case_t;",
        "",
    ]
    for case in cases:
        lines.append(f"static const double sofia_golden_samples_{case['name']}[] = {{")
        lines.append("    " + ", ".join(f"{v!r}" for v in case["samples"]))
        lines.append("};")
        lines.append(f"static const double sofia_golden_expected_{case['name']}[] = {{")
        values = [case["expected"][name] for name in STATISTICAL_FEATURE_NAMES]
        lines.append("    " + ", ".join(_c_double(v) for v in values))
        lines.append("};")
        lines.append("")

    lines.append("static const sofia_golden_case_t sofia_golden_cases[] = {")
    for case in cases:
        lines.append(
            f"    {{\"{case['name']}\", {case['n']}, {case['sample_rate']!r}, "
            f"sofia_golden_samples_{case['name']}, "
            f"sofia_golden_expected_{case['name']}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif /* SOFIA_GOLDEN_VECTORS_H */")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _c_double(value: float) -> str:
    if math.isnan(value) or math.isinf(value):
        return "0.0"
    return repr(float(value))


def main() -> int:
    cases = [build_case(spec) for spec in CASES]
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    write_header(cases, OUT_H)
    payload = {
        "tolerance": TOLERANCE,
        "feature_names": list(STATISTICAL_FEATURE_NAMES),
        "generator": "tools/gen_golden_vectors.py",
        "contract": "sofia.core.vibration@1.0",
        "cases": cases,
    }
    OUT_JSON.write_text(json.dumps(payload, sort_keys=True, indent=2) + "\n",
                        encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO_ROOT)}")
    print(f"wrote {OUT_JSON.relative_to(REPO_ROOT)}")
    print(f"cases: {', '.join(c['name'] for c in cases)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
